id: IC8A51BDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T18:42:30+00:00'
last_modified: '2022-06-15T17:45:27.542562+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8284
  title: ཕར་ཕྱིན་གྱི་མཐའ་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B8B5:
      image_group_id: I1KG15812
      title: Volume 1 of phar phyin gyi mtha' dpyod
      total_pages: 464
      order: 1
      base_file: B8B5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
